// Generated by gencpp from file my_custom_message/num_sum.msg
// DO NOT EDIT!


#ifndef MY_CUSTOM_MESSAGE_MESSAGE_NUM_SUM_H
#define MY_CUSTOM_MESSAGE_MESSAGE_NUM_SUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_custom_message
{
template <class ContainerAllocator>
struct num_sum_
{
  typedef num_sum_<ContainerAllocator> Type;

  num_sum_()
    : sum(0)  {
    }
  num_sum_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::my_custom_message::num_sum_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_custom_message::num_sum_<ContainerAllocator> const> ConstPtr;

}; // struct num_sum_

typedef ::my_custom_message::num_sum_<std::allocator<void> > num_sum;

typedef boost::shared_ptr< ::my_custom_message::num_sum > num_sumPtr;
typedef boost::shared_ptr< ::my_custom_message::num_sum const> num_sumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_custom_message::num_sum_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_custom_message::num_sum_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_custom_message

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'my_custom_message': ['/home/scp/ros-codes/catkin_ws/src/my_custom_message/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_custom_message::num_sum_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_custom_message::num_sum_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_custom_message::num_sum_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_custom_message::num_sum_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_custom_message::num_sum_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_custom_message::num_sum_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_custom_message::num_sum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::my_custom_message::num_sum_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_custom_message::num_sum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_custom_message/num_sum";
  }

  static const char* value(const ::my_custom_message::num_sum_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_custom_message::num_sum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sum\n\
";
  }

  static const char* value(const ::my_custom_message::num_sum_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_custom_message::num_sum_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct num_sum_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_custom_message::num_sum_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_custom_message::num_sum_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_CUSTOM_MESSAGE_MESSAGE_NUM_SUM_H
